# Generated by Django 5.0.3 on 2024-05-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehiculos',
        ),
    ]
