# Generated by Django 5.0.3 on 2024-05-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageApp', '0002_delete_vehiculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.BigIntegerField(),
        ),
    ]
