# Generated by Django 5.0.3 on 2024-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageApp', '0004_mensajewhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
