# Generated by Django 5.0.3 on 2024-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageApp', '0005_mensajewhatsapp_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='tarea_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
