# Generated by Django 5.0.3 on 2024-05-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageApp', '0006_mensajewhatsapp_tarea_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='tarea_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
